import './globals.css'

export const metadata = {
  title: 'React Newsbox',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const VERSION = "2.0"

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body>
        {children}
        <footer>
        <p>Vesion <span>{VERSION}</span></p>
      </footer>
      </body>
    </html>
  )
}
